export { default as HomeLayoutPage } from "./HomeLayoutPage";
export { default as LandingPage } from "./LandingPage";
export { default as SingleProductPage } from "./SingleProductPage";
export { default as ProductsPage } from "./ProductsPage";
export { default as CartPage } from "./CartPage";
export { default as ErrorPage } from "./ErrorPage";
export { default as AboutPage } from "./AboutPage";
export { default as CheckoutPage } from "./CheckoutPage";
export { default as OrdersPage } from "./OrdersPage";
